---
# tasks file for tomcat
- name: install tomcat
  apt: 
   name: tomcat8
   state: installed

- name: copy file
  copy: dest={{dst}}/hello-1.0.war src={{src}}/hello-1.0.war 
  notify:
   - restart tomcat

